version = 1

exclude_patterns = [  
  "node_modules/*",
  "assets/scripts/Other/adRecovery.js",
  "assets\scripts\Other\GoogleAnalytics.js",
  "assets\scripts\Other\GoogleAnalytics.min.js",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]
  module_system = "commonjs"