openapi: "3.0.0"
info:
  version: "1.1.2-dev"
  title: "FemDevs API Documentation"
  description: "The documentation for the FemDevs API"
paths:
  /user/get:
    get:
      operationId: "GetUser"
      description: ""
      parameters:
        - in: "header"
          name: "x-user-id"
          schema:
            type: "string"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
        400:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorData"
      security:
        - BearerAuth: []
  /crypt/enc:
    get:
      operationId: "CryptographyEnc"
      description: ""
      parameters:
        - in: "query"
          name: "data"
          schema:
            type: "string"
      responses:
        200:
          description: "The Encrypted Data"
          content:
            application/json:
              schema:
                type: "string"
        400:
          description: "Error With Encryption"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorData"
      security:
        - BearerAuth: []
  /crypt/decr:
    get:
      operationId: "CryptographyDecr"
      description: ""
      parameters:
        - in: "query"
          name: "data"
          schema:
            type: "string"
      responses:
        200:
          description: "The Decrypted Data"
          content:
            application/json:
              schema:
                type: "string"
        400:
          description: "Error with Decryption"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorData"
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
  schemas:
    UserInfo:
      properties:
        id:
          nullable: false
          type: "integer"
        name:
          nullable: false
          type: "string"
        picture:
          nullable: false
          type: "string"
        flags:
          nullable: false
          type: "integer"
        username:
          nullable: false
          type: "string"
    ErrorData:
      properties:
        code:
          nullable: false
          type: "integer"
        message:
          nullable: false
          type: "string"
        fatal:
          nullable: false
          type: "boolean"
