openapi: "3.0.0"
info:
  version: "1.1.2-dev"
  title: "FemDevs API Documentation"
  description: "The documentation for the FemDevs API. All endpoints have the root of `https://thefemdevs.com/api/`"
servers:
  - url: "https://thefemdevs.com/api/"
    description: "Production Server"
paths:
  /user/get:
    get:
      operationId: "GetUser"
      description: "Gets the user information for the user with the given ID"
      parameters:
        - in: "header"
          name: "x-user-id"
          schema:
            type: "string"
      responses:
        200:
          description: "The user information for the given ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
        400:
          description: "Error with the given ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorData"
      security:
        - BearerAuth: []
  /crypto/enc:
    get:
      operationId: "CryptographyEnc"
      description: "Crpytography endpoint for encrypting data"
      parameters:
        - in: "query"
          name: "data"
          schema:
            type: "string"
      responses:
        200:
          description: "The Encrypted Data"
          content:
            application/json:
              schema:
                type: "string"
        400:
          description: "Error With Encryption"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorData"
      security:
        - BearerAuth: []
  /crypto/dec:
    get:
      operationId: "CryptographyDecr"
      description: "Crpytography endpoint for decrypting data"
      parameters:
        - in: "query"
          name: "data"
          schema:
            type: "string"
      responses:
        200:
          description: "The Decrypted Data"
          content:
            application/json:
              schema:
                type: "string"
        400:
          description: "Error with Decryption"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorData"
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
  schemas:
    UserInfo:
      properties:
        id:
          nullable: false
          type: "integer"
        name:
          nullable: false
          type: "string"
        picture:
          nullable: false
          type: "string"
        flags:
          nullable: false
          type: "integer"
        username:
          nullable: false
          type: "string"
    ErrorData:
      properties:
        code:
          nullable: false
          type: "integer"
        message:
          nullable: false
          type: "string"
        fatal:
          nullable: false
          type: "boolean"
