name: CoSign

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  example:
    runs-on: ubuntu-latest
    permissions: {}
    name: Install Cosign
    steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.3.0
    - name: Check install!
      run: cosign version
    # check if the commit has a semver value in the commit message
    # if so, generate a zip archive of the code, sign the file,
    # and create a release in the repository with the signed file
    # and the release notes to be entered from a CHANGELOG.md file
    - name: Create Release
      if: contains(github.event.head_commit.message, 'v[0-9]+.[0-9]+.[0-9]+')
      run: |
        echo "Creating release"
        # get the version from the commit message
        version=$(echo ${{ github.event.head_commit.message }} | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')
        echo "Version: $version"
        # create a zip archive of the code
        zip -r code.zip .
        # sign the zip archive
        cosign sign -key cosign.key code.zip
        # create a release in the repository
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases -d "{\"tag_name\": \"$version\", \"name\": \"$version\", \"body\": \"$(cat CHANGELOG.md)\"}"
        # upload the signed zip archive to the release
        upload_url=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/tags/$version | jq -r .upload_url | sed 's/{?name,label}//')
        echo "Upload URL: $upload_url"
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/zip" --data-binary @code.zip $upload_url?name=code.zip
        # upload the public key to the release
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/pgp-keys" --data-binary @cosign.pub $upload_url?name=cosign.pub
    - name: Check for changes
      run: |
        echo "Checking for changes"
        # check if the commit has a CHANGELOG.md file
        if [ -f CHANGELOG.md ]; then
        echo "CHANGELOG.md exists"
        else
        echo "CHANGELOG.md does not exist"
        exit 1
        fi
        # check if the commit has a semver value in the commit message
        if [[ $(echo ${{ github.event.head_commit.message }} | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+') ]]; then
        echo "Semver value exists"
        else
        echo "Semver value does not exist"
        exit 1
        fi
    - name: Check for signed release
      run: |
        echo "Checking for signed release"
        # check if the release has a signed file
        if [[ $(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/tags/$version | jq -r .assets[0].name) ]]; then
        echo "Signed file exists"
        else
        echo "Signed file does not exist"
        exit 1
        fi
    - name: Check for public key
      run: |
        echo "Checking for public key"
        # check if the release has a public key
        if [[ $(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/tags/$version | jq -r .assets[1].name) ]]; then
        echo "Public key exists"
        else
        echo "Public key does not exist"
        exit 1
        fi