name: CoSign

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  example:
    runs-on: ubuntu-latest
    permissions: {}
    name: Install Cosign
    steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.3.0
    - name: Check install!
      run: cosign version
    # check if the commit has a semver value in the commit message
    # if so, generate a zip archive of the code, sign the file,
    # and create a release in the repository with the signed file
    # and the release notes to be entered from a CHANGELOG.md file
    - name: Create Release
      if: contains(github.event.head_commit.message, 'v[0-9]+.[0-9]+.[0-9]+')
      run: |
        echo "Creating release"
        # get the version from the commit message
        version=$(echo ${{ github.event.head_commit.message }} | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')
        echo "Version: $version"
        # filename
        fn = $version.zip
        # create a zip archive of the code
        zip -r $fn .
        # sign the zip archive
        cosign sign -key cosign.key code.zip
        # create a release in the repository
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases -d "{\"tag_name\": \"$version\", \"name\": \"$version\", \"body\": \"$(cat CHANGELOG.md)\"}"
        # upload the signed zip archive to the release
        upload_url=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/tags/$version | jq -r .upload_url | sed 's/{?name,label}//')
        echo "Upload URL: $upload_url"
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/zip" --data-binary @$fn $upload_url?name=$fn
        # upload the public key to the release
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/pgp-keys" --data-binary @cosign.pub $upload_url?name=cosign.pub