# name: CoSign

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# permissions:
#   contents: read
#   packages: write
#   id-token: write

# jobs:
#   example:
#     runs-on: ubuntu-latest
#     permissions: {}
#     name: Install Cosign
#     steps:
#     - name: Install Cosign
#       uses: sigstore/cosign-installer@v3.3.0
#     - name: Check install!
#       run: cosign version
#     - name: Sign
#       run: cosign sign -key cosign.key -a ${{ github.actor }}/$GITHUB_REPOSITORY:$GITHUB_SHA